# Enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

output_subdir: .

# saves run info so it can be used for reruns;
# see (https://hydra.cc/docs/experimental/rerun/)
callbacks:
  save_job_info:
    _target_: hydra.experimental.callbacks.PickleJobInfoCallback

# This makes hydra overwrite the logging instead of appending
job_logging:
  handlers:
    file:
      filename: ${hydra.run.dir}/${hydra.job.name}.log
      mode: w
