# @package _global_

defaults:
  - hydra: default.yaml
  - paths: default.yaml
  - _self_

get_best: false

project_name: cathode
# # With 1000 signal events
# # # Signal region
# # network_name: 2023-09-26_14-34-32-750364
# # Sideband region
# network_name: 2023-09-26_14-22-28-287472
# With 8000 signal events
# # Signal region
# network_name: 2023-09-28_09-44-37-358019
# # Sideband region
# network_name: 2023-09-28_09-51-15-071996
# With 1000 signal events and real modelling
# # Signal region
# network_name: 2023-09-28_10-51-26-687232
# Sideband region
network_name: 2023-09-28_10-18-57-577992

bands:
  - sr_signal
  - sr
