full_run_cfg: "twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b.yaml"

# Change the seed for the template training
several_template_train_seeds: [1, 2, 3] 

# Change the number of signal events doped 
several_doping: [0, 50, 100, 333, 500, 667, 1000, 3000]
check_doping: 3000 #a value from the original config file to replace