full_run_cfg: "twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b.yaml"
run_dir: "None"
# Change the seed for the template training
several_template_train_seeds: [1, 2, 3] 

# Change the number of signal events doped 
several_doping: [0, 50, 100, 333, 500, 667, 1000, 3000]
check_doping: 3000 #a value from the original config file to replace
redo: False
run_sequentially: True # Run the experiments sequentially
do_stability_analysis: True
not_just_seeds: True

stability_analysis_cfg:
  run_dir: null
  save_curves: True
  postfix: "comb_seeds_CWOLA"

  main_methods:
    TwinTurbo: 
      rel_directory: "/"
      prefix: "TwinTurbo_"
      postfix: "_comb_CWOLA"
    TwinTurboLatent: 
      rel_directory : "/"
      prefix: "TwinTurboLatent_"
      postfix: "_comb_CWOLA"


  methods: #"CURTAINS": "/home/users/o/oleksiyu/WORK/hyperproject/lit/curtains/run_7",
    supervised: 
      abs_directory: "/home/users/o/oleksiyu/WORK/hyperproject/lit/radot/dope_3000/supervised"
      prefix: ""
      postfix: ""
    idealised: 
      abs_directory: "/home/users/o/oleksiyu/WORK/hyperproject/lit/radot/dope_3000/idealised"
      prefix: ""
      postfix: ""
    radot: 
      abs_directory: "/home/users/o/oleksiyu/WORK/hyperproject/lit/radot/dope_3000/standard"
      prefix: ""
      postfix: ""