# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCOllv_hlv
  - step_train_template: twinturbo_reco_adv
  - step_export_template: twinturbo_LHCO_hlv
  - step_evaluate: twinturbo_LHCO_fast
  - step_cwola: BDT_LHCO_allCWOLA
  - step_export_latent: twinturbo_LHCO
  - step_plot_compare: twinturbo_LHCO
  - override step_train_template/model: TRANSIT_llv_v3.yaml
  - override step_train_template/trainer: 500e_noclip.yaml
  - override step_train_template/model/optimizer: AdamW_lr2-4

step_train_template:
  model:
    reverse_pass_mode: additional_input
    valid_plots: False

do_train_template: True
do_export_template: True
do_export_latent: False
do_evaluation: False
do_cwola: False
do_evaluate_cwola: False
do_plot_compare: False

verbose_validation: True

general:
  name: TRANSIT_LLV_v3
  subfolder: 2024_09_09/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}