# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCO_DEFAULT_speed
  - step_train_template: twinturbo_reco_adv
  - step_export_template: twinturbo_LHCO
  - step_export_SB1: twinturbo_LHCO
  - step_export_SB2: twinturbo_LHCO
  - step_evaluate: twinturbo_LHCO_fast
  - step_cwola: BDT_LHCO_allCWOLA
  - step_export_latent: twinturbo_LHCO
  - step_plot_compare: twinturbo_LHCO
  - override step_train_template/model: TRANSITv25f
  - override step_train_template/trainer: 200e_noclip.yaml
  - override step_train_template/model/optimizer: AdamW_lr2-4


step_train_template:
  model:
    reverse_pass_mode: additional_input
    valid_plots: False
    afterglow_epoch: 999999999

do_train_template: True
do_export_template: True
do_export_latent: True
do_evaluation: True
do_cwola: True
do_evaluate_cwola: True
do_plot_compare: True

do_transport_sideband: True

verbose_validation: False

general:
  name: TRANSITv0v2
  subfolder: TEST/
  seed: 12345 # For reproducibility
  run_dir: workspaces/${general.subfolder}${general.name}
