# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCO_DEFAULT
  - step_train_template: twinturbo_reco_adv
  - step_export_template: twinturbo_LHCO
  - step_export_SB1: twinturbo_LHCO
  - step_export_SB2: twinturbo_LHCO
  - step_evaluate: twinturbo_LHCO_fast
  - step_cwola: BDT_LHCO_allCWOLA
  - step_export_latent: twinturbo_LHCO
  - step_plot_compare: twinturbo_LHCO
  - override step_train_template/model: TRANSITv15f
  - override step_train_template/trainer: 200e_noclip.yaml
  - override step_train_template/model/optimizer: AdamW_lr2-4


step_train_template:
  model:
    reverse_pass_mode: additional_input
    valid_plots: False
    afterglow_epoch: 999999999

do_train_template: False
do_export_template: False
do_export_latent: False
do_evaluation: True
do_cwola: False
do_evaluate_cwola: False
do_plot_compare: False

do_transport_sideband: True

verbose_validation: False

general:
  name: TRANSITv15f
  subfolder: ML4Jets/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
