# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCOp_twinturbo_CATHODE_addgapmass2048b_dl
  - step_train_template: twinturbo_reco_adv
  - step_export_template: twinturbo_LHCO
  - step_evaluate: twinturbo_LHCO
  - step_cwola: BDT_LHCO_allCWOLA
  - step_export_latent: twinturbo_LHCO
  - step_plot_compare: twinturbo_LHCO
  - override step_train_template/model: twinturbo_reco_cons0.001_smls0.0001_adv38
  - override step_train_template/trainer: 800e_noclip.yaml
  - override step_train_template/model/optimizer: AdamW_lr2-4
  - override step_train_template/model/scheduler: MultiStepLR

step_train_template:
  model:
    reverse_pass_mode: additional_input

do_train_template: True
do_export_template: True
do_export_latent: True
do_evaluation: True
do_cwola: True
do_evaluate_cwola: True
do_plot_compare: True

general:
  name: TT_reco_cons0.001_smls0.0001_adv38_LCR_2048b_lr2-4_dl
  subfolder: REFERENCE13_08onGPU033/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
