# @package _global_

defaults:
  - _self_
  - path: user
<<<<<<< HEAD
  - data: LHCOllv_hlv
  - step_train_template: twinturbo_reco_adv
  - step_export_template: twinturbo_LHCO_hlv
=======
  - data: LHCOlow_hlv
  - step_train_template: twinturbo_reco_adv
  - step_export_template: twinturbo_LHCO_HVL
>>>>>>> 4dffb3b (some unclear CUDA errors)
  - step_evaluate: twinturbo_LHCO_fast
  - step_cwola: BDT_LHCO_allCWOLA
  - step_export_latent: twinturbo_LHCO
  - step_plot_compare: twinturbo_LHCO
<<<<<<< HEAD
  - override step_train_template/model: twinturbo_reco_advII5std_llv
  - override step_train_template/trainer: 1e_noclip.yaml
=======
  - override step_train_template/model: twinturbo_reco_cons0.001_smls0.0001_advII5nrm_llv
  - override step_train_template/trainer: 1000e_noclip.yaml
>>>>>>> 4dffb3b (some unclear CUDA errors)
  - override step_train_template/model/optimizer: AdamW_lr2-4

step_train_template:
  model:
    reverse_pass_mode: additional_input
    valid_plots: False

do_train_template: False
do_export_template: True
do_export_latent: False
do_evaluation: False
do_cwola: False
do_evaluate_cwola: False
do_plot_compare: False

verbose_validation: True

general:
<<<<<<< HEAD
  name: TT_reco_cons0.001_smls0.0001_advII5s_LLV_2048b_lr2-4_dl
  subfolder: devvvv/
=======
  name: TT_reco_cons0.001_smls0.0001_advII5s_HLV_2048b_lr2-4_dl
  subfolder: REFERENCE13_08onGPU033/
>>>>>>> 4dffb3b (some unclear CUDA errors)
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
