# @package _global_

defaults:
  - _self_
  - path: user
  - data: gauss_corr_2_twinturbo_usem
  - step_train_template: twinturbo_reco_noise_mINx
  - step_export_template: twinturbo
  - step_evaluate: twinturbo


do_train_template: True
do_export_template: True
do_train_cwola: False
do_evaluate_cwola: False
do_evaluation: True 


general:
  name: twinturbo_reco_noise_mINx
  subfolder: experiments/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}

