# @package _global_

defaults:
  - _self_
  - path: io_surface_wsl
  - data: gauss_corr_2_10K_twinturbo_usem
  - step_train_template: twinturbo_dev
  - step_export_template: twinturbo_LHCO
  - step_evaluate: twinturbo_LHCO_debug


do_train_template: True
do_export_template: True
do_train_cwola: False
do_evaluate_cwola: False
do_evaluation: True 

general:
  name: twinTURBO_test
  subfolder: test/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
