# @package _global_

defaults:
  - _self_
  - path: user
  - data: gauss_corr_4_gap_twinturbo_usem
  - step_train_template: twinturbo_dev
  - step_export_template: twinturbo
  - step_evaluate: twinturbo_debug
  - step_cwola: BDT_LHCO.yaml


do_train_template: False
do_export_template: False
do_cwola: False
do_evaluation: True 

general:
  name: twinTURBo_gap1
  subfolder: test/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
