step_train_template:
  model:
    reverse_pass_mode: additional_input
    _target_: twinturbo.src.models.twinturbo_model.TwinTURBO
    use_m: true
    encoder_mlp_config:
      hddn_dim:
      - 64
      - 64
      - 64
      - 64
      act_h: prelu
    decoder_mlp_config:
      hddn_dim:
      - 64
      - 64
      - 64
      - 64
      act_h: prelu
    latent_norm: true
    latent_dim: 8
    loss_cfg:
      reco:
        w: 1
      DisCO_loss_cfg:
        w: 0.01
      second_derivative_smoothness:
        w: 0.1
        step: 0.01
    optimizer:
      _target_: torch.optim.AdamW
      _partial_: true
      lr: 0.0001
      weight_decay: 1.0e-05
    scheduler:
      scheduler:
        _target_: torch.optim.lr_scheduler.CosineAnnealingLR
        _partial_: true
        T_max: 100000
        last_epoch: -1
        eta_min: 0
      lightning:
        monitor: valid/log_prob
        interval: step
        frequency: 1
  project_name: twinTURBO_gauss_corr
  network_name: twinturbo_reco_DisCo_massfromgap_smooth_2024-07-09_14-00-02-406163
  ckpt_path: null
  precision: high
  compile: null
  full_resume: false
  seed: 12345
  callbacks:
    model_checkpoint:
      _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/template/checkpoints
      filename: best_{epoch:03d}
      monitor: valid/total_loss
      mode: min
      save_last: true
      auto_insert_metric_name: false
    model_summary:
      _target_: pytorch_lightning.callbacks.RichModelSummary
      max_depth: 2
    lr_monitor:
      _target_: pytorch_lightning.callbacks.LearningRateMonitor
      logging_interval: step
  loggers:
    wandb:
      _target_: pytorch_lightning.loggers.wandb.WandbLogger
      offline: true
      id: null
      log_model: false
      project: twinTURBO_gauss_corr
      name: twinturbo_reco_DisCo_massfromgap_smooth_2024-07-09_14-00-02-406163
      save_dir: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth
      resume: false
  paths:
    output_dir: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/template
    root_dir: /home/users/o/oleksiyu/WORK/hyperproject
    full_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/template
    wandbkey: /home/users/o/oleksiyu/WORK/keys/wandb.key
  trainer:
    _target_: pytorch_lightning.Trainer
    min_epochs: 1
    max_epochs: 100
    enable_progress_bar: true
    accelerator: auto
    devices: 1
    gradient_clip_val: 5
    precision: 32
    check_val_every_n_epoch: 1
    default_root_dir: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/template
  data:
    datamodule:
      _target_: twinturbo.src.data.data.SimpleDataModule
      train_frac: 0.8
      train_data:
        _target_: twinturbo.src.data.data.CombDataset
        dataset1:
          _target_: twinturbo.src.data.data.InMemoryDataFrameDict
          list_order:
          - data
          - mass
          file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
          plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
          processor_cfg:
          - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
            frame_name: data
            new_df_dict:
              data:
              - x1
              - x2
              - x3
              - x0
              mass:
              - x0
          - _target_: twinturbo.src.data.data.ProcessorIntervals
            scalar_df_name: mass
            var_name: x0
            intervals:
            - - -100000
              - -0.5
            - - 0.5
              - 100000
          - _target_: twinturbo.src.data.data.ProcessorToFloat32
            frame_names:
            - data
            - mass
        dataset2:
          _target_: twinturbo.src.data.data.InMemoryDataFrameDict
          list_order:
          - mass_add
          file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
          plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
          processor_cfg:
          - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
            frame_name: data
            new_df_dict:
              mass_add:
              - x0
          - _target_: twinturbo.src.data.data.ProcessorShuffle
          - _target_: twinturbo.src.data.data.ProcessorToFloat32
            frame_names:
            - mass_add
      loader_kwargs:
        pin_memory: true
        batch_size: 512
        num_workers: 8
        drop_last: false
do_train_template: true
do_export_template: true
do_cwola: false
do_evaluate_cwola: false
do_evaluation: true
general:
  name: twinturbo_reco_DisCo_massfromgap_smooth
  subfolder: gauss_corr_4_gap_twinturbo_usem_addgapmass/
  seed: 12345
  run_dir: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth
path:
  hyperproject: /home/users/o/oleksiyu/WORK/hyperproject
  wandbkey: /home/users/o/oleksiyu/WORK/keys/wandb.key
data:
  template_training:
    _target_: twinturbo.src.data.data.SimpleDataModule
    train_frac: 0.8
    train_data:
      _target_: twinturbo.src.data.data.CombDataset
      dataset1:
        _target_: twinturbo.src.data.data.InMemoryDataFrameDict
        list_order:
        - data
        - mass
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
        plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
        processor_cfg:
        - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
          frame_name: data
          new_df_dict:
            data:
            - x1
            - x2
            - x3
            - x0
            mass:
            - x0
        - _target_: twinturbo.src.data.data.ProcessorIntervals
          scalar_df_name: mass
          var_name: x0
          intervals:
          - - -100000
            - -0.5
          - - 0.5
            - 100000
        - _target_: twinturbo.src.data.data.ProcessorToFloat32
          frame_names:
          - data
          - mass
      dataset2:
        _target_: twinturbo.src.data.data.InMemoryDataFrameDict
        list_order:
        - mass_add
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
        plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
        processor_cfg:
        - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
          frame_name: data
          new_df_dict:
            mass_add:
            - x0
        - _target_: twinturbo.src.data.data.ProcessorShuffle
        - _target_: twinturbo.src.data.data.ProcessorToFloat32
          frame_names:
          - mass_add
    loader_kwargs:
      pin_memory: true
      batch_size: 512
      num_workers: 8
      drop_last: false
  export_template:
    _target_: twinturbo.src.data.data.SimpleDataModule
    train_frac: 0.8
    loader_kwargs:
      pin_memory: true
      batch_size: 512
      num_workers: 8
      drop_last: false
    test_data:
      _target_: twinturbo.src.data.data.CombDataset
      plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/export/
      dataset1:
        _target_: twinturbo.src.data.data.InMemoryDataFrameDict
        list_order:
        - data
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
        plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
        processor_cfg:
        - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
          frame_name: data
          new_df_dict:
            data:
            - x1
            - x2
            - x3
            - x0
            mass:
            - x0
        - _target_: twinturbo.src.data.data.ProcessorIntervals
          scalar_df_name: data
          var_name: x0
          intervals:
          - - -100000
            - -0.5
          - - 0.5
            - 100000
        - _target_: twinturbo.src.data.data.ProcessorToFloat32
          frame_names:
          - data
      dataset2:
        _target_: twinturbo.src.data.data.InMemoryDataFrameDict
        list_order:
        - mass
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
        plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
        processor_cfg:
        - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
          frame_name: data
          new_df_dict:
            mass:
            - x0
        - _target_: twinturbo.src.data.data.ProcessorIntervals
          scalar_df_name: mass
          var_name: x0
          intervals:
          - - -0.5
            - 0.5
        - _target_: twinturbo.src.data.data.ProcessorShuffle
        - _target_: twinturbo.src.data.data.ProcessorToFloat32
          frame_names:
          - mass
  evaluation:
    original_data:
      _target_: twinturbo.src.data.data.InMemoryDataFrameDict
      list_order:
      - data
      - mass
      file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
      plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
      processor_cfg:
      - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
        frame_name: data
        new_df_dict:
          data:
          - x1
          - x2
          - x3
          - x0
          mass:
          - x0
      - _target_: twinturbo.src.data.data.ProcessorIntervals
        scalar_df_name: mass
        var_name: x0
        intervals:
        - - -100000
          - -0.5
        - - 0.5
          - 100000
    target_data:
      _target_: twinturbo.src.data.data.InMemoryDataFrameDict
      list_order:
      - data
      - mass
      file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
      plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
      processor_cfg:
      - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
        frame_name: data
        new_df_dict:
          data:
          - x1
          - x2
          - x3
          - x0
          mass:
          - x0
      - _target_: twinturbo.src.data.data.ProcessorIntervals
        scalar_df_name: mass
        var_name: x0
        intervals:
        - - -0.5
          - 0.5
  cwola:
    experimental_data:
      _target_: twinturbo.src.data.data.InMemoryDataFrameDict
      list_order:
      - data
      - mass
      file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
      plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
      processor_cfg:
      - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
        frame_name: data
        new_df_dict:
          data:
          - x1
          - x2
          - x3
          - x0
          mass:
          - x0
      - _target_: twinturbo.src.data.data.ProcessorIntervals
        scalar_df_name: mass
        var_name: x0
        intervals:
        - - -0.5
          - 0.5
step_export_template:
  seed: 12345
  data:
    _target_: twinturbo.src.data.data.SimpleDataModule
    train_frac: 0.8
    loader_kwargs:
      pin_memory: true
      batch_size: 512
      num_workers: 8
      drop_last: false
    test_data:
      _target_: twinturbo.src.data.data.CombDataset
      plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/export/
      dataset1:
        _target_: twinturbo.src.data.data.InMemoryDataFrameDict
        list_order:
        - data
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
        plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
        processor_cfg:
        - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
          frame_name: data
          new_df_dict:
            data:
            - x1
            - x2
            - x3
            - x0
            mass:
            - x0
        - _target_: twinturbo.src.data.data.ProcessorIntervals
          scalar_df_name: data
          var_name: x0
          intervals:
          - - -100000
            - -0.5
          - - 0.5
            - 100000
        - _target_: twinturbo.src.data.data.ProcessorToFloat32
          frame_names:
          - data
      dataset2:
        _target_: twinturbo.src.data.data.InMemoryDataFrameDict
        list_order:
        - mass
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
        plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
        processor_cfg:
        - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
          frame_name: data
          new_df_dict:
            mass:
            - x0
        - _target_: twinturbo.src.data.data.ProcessorIntervals
          scalar_df_name: mass
          var_name: x0
          intervals:
          - - -0.5
            - 0.5
        - _target_: twinturbo.src.data.data.ProcessorShuffle
        - _target_: twinturbo.src.data.data.ProcessorToFloat32
          frame_names:
          - mass
  paths:
    full_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/template
    output_dir: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/template
  output_name: template_sample
  get_best: false
  project_name: CATHODE_LHCO
  network_name: twinturbo_reco_DisCo_massfromgap_smooth_2024-07-09_14-00-02-406163
step_evaluate:
  original_data:
    _target_: twinturbo.src.data.data.InMemoryDataFrameDict
    list_order:
    - data
    - mass
    file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
    plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
    processor_cfg:
    - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
      frame_name: data
      new_df_dict:
        data:
        - x1
        - x2
        - x3
        - x0
        mass:
        - x0
    - _target_: twinturbo.src.data.data.ProcessorIntervals
      scalar_df_name: mass
      var_name: x0
      intervals:
      - - -100000
        - -0.5
      - - 0.5
        - 100000
  target_data:
    _target_: twinturbo.src.data.data.InMemoryDataFrameDict
    list_order:
    - data
    - mass
    file_path: /home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_corr_4.h5
    plotting_path: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/plots/train/
    processor_cfg:
    - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
      frame_name: data
      new_df_dict:
        data:
        - x1
        - x2
        - x3
        - x0
        mass:
        - x0
    - _target_: twinturbo.src.data.data.ProcessorIntervals
      scalar_df_name: mass
      var_name: x0
      intervals:
      - - -0.5
        - 0.5
  template_file: twinturbo/workspaces/gauss_corr_4_gap_twinturbo_usem_addgapmass/twinturbo_reco_DisCo_massfromgap_smooth/template/outputs/template_sample.h5
  debug_eval: false
