# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCO_twinturbo_CATHODE_addgapmass
  - step_train_template: twinturbo_reco_DisCo_smooth
  - step_export_template: twinturbo_LHCO
  - step_evaluate: twinturbo_LHCO
  - override step_train_template/model: twinturbo_reco_DisCo_smooth_shed2elu
  - override step_train_template/callbacks: default_noearly.yaml

step_train_template:
  model:
    reverse_pass_mode: additional_input

do_train_template: True
do_export_template: True
do_cwola: False
do_evaluate_cwola: False
do_evaluation: True 

general:
  name: twinturbo_reco_DisCo_massfromgap_smooth_shed2elu_LHCO_CURTAINS
  subfolder: LHCO/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}


