# @package _global_

defaults:
  - _self_
  - path: user
  - data: gauss_corr_2_10K_twinturbo_usem
  - step_train_template: twinturbo_dev
  - step_export_template: twinturbo
  - step_evaluate: twinturbo
  - step_cwola: BDT_LHCO.yaml


do_train_template: True
do_export_template: False
do_cwola: False
do_evaluation: False 

general:
  name: twinTURBO_test
  subfolder: test/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
