# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCOp_twinturbo_CATHODE_addgapmass1024b
  - step_train_template: twinturbo_reco_adv
  - step_export_template: twinturbo_LHCO
  - step_evaluate: twinturbo_LHCO
  - step_cwola: BDT_LHCO_allCWOLA
  - step_export_latent: twinturbo_LHCO
  - step_plot_compare: twinturbo_LHCO
  - override step_train_template/model: twinturbo_reco_cons0.01_smls0.001_adv3
  - override step_train_template/trainer: 300e_noclip.yaml


step_train_template:
  model:
    reverse_pass_mode: additional_input

do_train_template: True
do_export_template: True
do_export_latent: True
do_evaluation: True
do_cwola: True
do_evaluate_cwola: True
do_plot_compare: True

general:
  name: twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS1024b_long
  subfolder: adv_main/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
