# @package _global_

defaults:
  - _self_
  - path: user
  - data: gauss_corr_4_gap_twinturbo_usem_addgapmass
  - step_train_template: twinturbo_reco_cons_DisCo
  - step_export_template: twinturbo
  - step_evaluate: twinturbo

step_train_template:
  model:
    reverse_pass_mode: additional_input

do_train_template: True
do_export_template: True
do_cwola: False
do_evaluate_cwola: False
do_evaluation: True 


general:
  name: twinturbo_reco_cons_DisCo_massfromgap
  subfolder: experiments/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}

