# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCO_twinturbo_CATHODE_addgapmass1024b
  - step_train_template: twinturbo_reco_adv
  - step_export_template: twinturbo_LHCO
  - step_evaluate: twinturbo_LHCO
  - step_cwola: BDT_LHCO_3000sig
  - override step_train_template/model: twinturbo_reco_cons0.01_smls0.001_adv3
  - override step_train_template/trainer: 100e_noclip.yaml

step_train_template:
  model:
    reverse_pass_mode: additional_input

do_train_template: False
do_export_template: False
do_cwola: True
do_evaluate_cwola: False
do_evaluation: False 


general:
  name: twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS1024b
  subfolder: adv1_gauss_corr_4_gap_twinturbo_usem_addgapmass/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
