# @package _global_

defaults:
  - _self_
  - data: LHCO_twinturbo
  - step_train_template: twinturbo_reco_DisCo
  - step_export_template: twinturbo
  - step_evaluate: twinturbo


do_train_template: False
do_export_template: True
do_train_cwola: False
do_evaluate_cwola: False
do_evaluation: True 


general:
  name: twinturbo_reco_DisCo_LHCO_CURTAINS
  subfolder: LHCO/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
