# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCO_twinturbo_CATHODE
  - step_train_template: twinturbo_reco_cons_DisCo
  - step_export_template: twinturbo_LHCO
  - step_evaluate: twinturbo_LHCO


do_train_template: True
do_export_template: True
do_train_cwola: False
do_evaluate_cwola: False
do_evaluation: True 


general:
  name: twinturbo_reco_cons_DisCo_LHCO_CURTAINS
  subfolder: LHCO/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
