# @package _global_

defaults:
  - _self_
  - path: user
  - data: gauss_corr_4_gap_twinturbo_usem_addgapmass2048
  - step_train_template: twinturbo_reco_DisCo_smooth
  - step_export_template: twinturbo
  - step_evaluate: twinturbo
  - override step_train_template/model: twinturbo_reco_cons0.001_DisCo_smooth_shed7elu
  - override step_train_template/callbacks: default_noearly.yaml
  - override step_train_template/trainer: 300e.yaml

step_train_template:
  model:
    reverse_pass_mode: additional_input

do_train_template: True
do_export_template: True
do_cwola: False
do_evaluate_cwola: False
do_evaluation: True 


general:
  name: twinturbo_reco_cons0.001_DisCo_massfromgap_smooth_shed7elu2048
  subfolder: experiments/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}

