model:
  reverse_pass_mode: additional_input
  _target_: twinturbo.src.models.twinturbo_model.TwinTURBO
  use_m: true
  encoder_mlp_config:
    hddn_dim:
    - 64
    - 64
    - 64
    - 64
    act_h: prelu
  decoder_mlp_config:
    hddn_dim:
    - 64
    - 64
    - 64
    - 64
    act_h: prelu
  latent_norm: true
  latent_dim: 8
  loss_cfg:
    reco:
      w: 1
    consistency_x:
      w: 0.01
    consistency_cont:
      w: 0.01
    second_derivative_smoothness:
      w: 0.001
      step: 0.1
  adversarial_cfg:
    discriminator:
      hddn_dim:
      - 64
      - 64
      - 64
      - 64
      act_h: prelu
    optimizer_main: default.yaml
    optimizer_d: default.yaml
    warmup: 20
    g_loss_weight: 0.2
    every_n_steps_g: 1
    train_dis_in_warmup: false
    g_loss_weight_in_warmup: true
  valid_plots: false
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.0001
    weight_decay: 1.0e-05
  scheduler:
    scheduler:
      _target_: torch.optim.lr_scheduler.CosineAnnealingLR
      _partial_: true
      T_max: 100000
      last_epoch: -1
      eta_min: 0
    lightning:
      monitor: valid/log_prob
      interval: step
      frequency: 1
project_name: twinTURBO_gauss_corr
network_name: twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b_2024-08-27_19-05-36-900316
ckpt_path: null
precision: high
compile: null
full_resume: false
seed: 1
automatic_optimization: false
callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: groups/twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b//run-TTS_1/template/checkpoints
    filename: min_val_loss_{epoch:03d}
    monitor: valid/total_loss
    mode: min
    save_last: true
    auto_insert_metric_name: false
  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: 2
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
loggers:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    offline: true
    id: lop4rri4
    log_model: false
    project: twinTURBO_gauss_corr
    name: twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b_2024-08-27_19-05-36-900316
    save_dir: groups/twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b//run-TTS_1
    resume: false
paths:
  output_dir: groups/twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b//run-TTS_1/template
  root_dir: /home/users/o/oleksiyu/WORK/hyperproject
  full_path: groups/twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b//run-TTS_1/template
  wandbkey: /home/users/o/oleksiyu/WORK/keys/wandb.key
trainer:
  _target_: pytorch_lightning.Trainer
  min_epochs: 1
  max_epochs: 200
  enable_progress_bar: true
  accelerator: auto
  devices: 1
  precision: 32
  check_val_every_n_epoch: 1
  default_root_dir: groups/twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b//run-TTS_1/template
data:
  datamodule:
    _target_: twinturbo.src.data.data.SimpleDataModule
    train_frac: 0.8
    train_data:
      _target_: twinturbo.src.data.data.CombDataset
      dataset1:
        _target_: twinturbo.src.data.data.InMemoryDataFrameDict
        list_order:
        - data
        - mass
        file_path: /home/users/o/oleksiyu/scratch/DATA/LHCO/events_anomalydetection_v2.features_prepCURTAINS.h5
        plotting_path: groups/twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b//run-TTS_1/plots/input/train_d1/
        processor_cfg:
        - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
          frame_name: df
          new_df_dict:
            data:
            - m_j1
            - del_m
            - del_R
            - tau21_j1
            - tau21_j2
            - m_jj
            is_signal:
            - is_signal
        - _target_: twinturbo.src.data.data.ProcessorApplyCuts
          scalar_df_name: is_signal
          cuts:
          - is_signal == 0
        - _target_: twinturbo.src.data.data.ProcessorIntervals
          scalar_df_name: data
          var_name: m_jj
          intervals:
          - - 3000
            - 3300
          - - 3700
            - 4600
        - _target_: twinturbo.src.data.data.ProcessorCATHODE
          frame_name: data
          save_pkl: groups/twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b//run-TTS_1/cathode_preprocessor.pkl
        - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
          frame_name: data
          new_df_dict:
            data:
            - m_j1
            - del_m
            - del_R
            - tau21_j1
            - tau21_j2
            - m_jj
            mass:
            - m_jj
        - _target_: twinturbo.src.data.data.ProcessorToFloat32
          frame_names:
          - data
          - mass
      dataset2:
        _target_: twinturbo.src.data.data.InMemoryDataFrameDict
        list_order:
        - mass_add
        file_path: /home/users/o/oleksiyu/scratch/DATA/LHCO/events_anomalydetection_v2.features_prepCURTAINS.h5
        plotting_path: groups/twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b//run-TTS_1/plots/input/train_d2/
        processor_cfg:
        - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
          frame_name: df
          new_df_dict:
            data:
            - m_j1
            - del_m
            - del_R
            - tau21_j1
            - tau21_j2
            - m_jj
            is_signal:
            - is_signal
        - _target_: twinturbo.src.data.data.ProcessorApplyCuts
          scalar_df_name: is_signal
          cuts:
          - is_signal == 0
        - _target_: twinturbo.src.data.data.ProcessorIntervals
          scalar_df_name: data
          var_name: m_jj
          intervals:
          - - 3000
            - 4600
        - _target_: twinturbo.src.data.data.ProcessorCATHODE
          frame_name: data
          load_pkl: groups/twinturbo_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b//run-TTS_1/cathode_preprocessor.pkl
        - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
          frame_name: data
          new_df_dict:
            mass_add:
            - m_jj
        - _target_: twinturbo.src.data.data.ProcessorToFloat32
          frame_names:
          - mass_add
    loader_kwargs:
      pin_memory: true
      batch_size: 2048
      num_workers: 8
      drop_last: false
