_target_: twinturbo.src.models.models.BaseFlow

normaliser_config:
  max_n: 1_000_000

base_model:
  _target_: twinturbo.src.models.models.NflowsWrap
  _partial_: True
  # how to use transform config directory instead?
  transform:
    _target_: flows4flows.ffflows.utils.spline_inn
    _partial_: True
    nodes: 128
    num_blocks: 2
    num_stack: 10
    num_bins: 8
    tail_bound: 4.0
    context_features: 1
    activation:
      _target_: flows4flows.ffflows.utils.get_activation
      name: 'leaky_relu'
  distribution: 
    _partial_: True
    _target_: nflows.distributions.StandardNormal

defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml
