seed: ${general.seed} 
data: ${data.export_template} 

paths:
  # output dir will be created by hydra
  full_path:  ${general.run_dir}/template
  output_dir:  ${general.run_dir}/template

signal_contamination_ns: [0, 1000, 1500, 2000, 2500, 3000, 4000]

get_best: false
project_name: CATHODE_LHCO
network_name: ${step_train_template.network_name}