scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: True
  T_max: 100_000
  last_epoch: -1
  eta_min: 0
lightning:
  monitor: valid/log_prob
  interval: step
  frequency: 1
