
original_data: ${data.evaluation.original_data}
target_data: ${data.evaluation.target_data}
template_file:  ${general.run_dir}/template/outputs/template_sample0.h5
debug_eval: True
get_best: False

procedures:
  plot_contour: False
  mass_correlation_plots: False
  
