# output dir will be created by hydra
output_dir: /Users/samklein/PycharmProjects/twinturbo/results

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}
