# @package _global_

defaults:
  - _self_
  - path: user
  - data: powers_5_gap_twinturbo_usem_addgapmass2048b
  - step_train_template: twinturbo_reco_adv
  - step_export_template: twinturbo
  - step_evaluate: twinturbo
  - override step_train_template/model: twinturbo_reco_cons0.01_smls0.001_adv3
  - override step_train_template/trainer: 100e_noclip.yaml


step_train_template:
  model:
    reverse_pass_mode: additional_input

do_train_template: False
do_export_template: Flase
do_export_latent: False
do_evaluation: True

general:
  name: twinturbo_reco_cons0.01_smls0.001_adv3_5p_massfromgap
  subfolder: 5p_massfromgap/
  seed: 12345 # For reproducibility
  run_dir: twinturbo/workspaces/${general.subfolder}${general.name}
