# Enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# To allow hydra to change the current working directory when running the file
job:
  chdir: True

searchpath:
  - /home/users/o/oleksiyu/WORK/hyperproject

# Interpolated variables output directory, generated dynamically on each run
run:
  dir: ${paths.full_path}

output_subdir: null

# This makes hydra overwrite the logging instead of appending
job_logging:
  handlers:
    file:
      mode: w
