run_dir: /home/users/o/oleksiyu/WORK/hyperproject/workspaces/groups/transit_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b
save_curves: True
postfix: "comb_seeds_CWOLA"

main_methods:
  transit: 
    abs_directory: /home/users/o/oleksiyu/WORK/hyperproject/workspaces/groups/transit_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b
    prefix: "transit_"
    postfix: "_comb_CWOLA"
  transitLatent: 
    abs_directory: /home/users/o/oleksiyu/WORK/hyperproject/workspaces/groups/transit_reco_cons0.01_smls0.001_adv3_LHCO_CURTAINS2048b
    prefix: "transitLatent_"
    postfix: "_comb_CWOLA"


methods: #"CURTAINS": "/home/users/o/oleksiyu/WORK/hyperproject/lit/curtains/run_7",
  supervised: 
    abs_directory: "/home/users/o/oleksiyu/WORK/hyperproject/lit/radot/dope_3000/supervised"
    prefix: ""
    postfix: ""
  idealised: 
    abs_directory: "/home/users/o/oleksiyu/WORK/hyperproject/lit/radot/dope_3000/idealised"
    prefix: ""
    postfix: ""
  radot: 
    abs_directory: "/home/users/o/oleksiyu/WORK/hyperproject/lit/radot/dope_3000/standard"
    prefix: ""
    postfix: ""