defaults:
  - _self_
  - load_predict_set: mnist
  - plot_def: rocs
  - hydra: default
  - common: private # create your own and never push! look at default for reference

io:
  checkpoint_path: result.ckpt
  prediction_paths: null
  output_path: plots.pdf
