defaults:
  - _self_

  - model: cnn
  - datamodule: mnist

  - trainer: default

  - hydra: default
  - common: private # create your own and never push! look at default for reference

id: debug # unique identifier for this particular training, useful for logging
seed: 0

# from which checkpoint to start the training; if it doesn't exist, start from scratch (usual case)
init_ckpt_path: "last"

io:
  dataset_path: .
  checkpoints_path: checkpoints
  result_path: result.ckpt
  trainer_root: .
  logging_dir: .
