defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m_encodig: True
encoder_cfg: 
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
decoder_cfg:
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
latent_norm: True
latent_dim: 8

loss_cfg:
  reco:
    w: 1
  attractive:
    w: 0.02
  repulsive:
    w: 0.01
  consistency_x:
    w: 0.1
  consistency_cont:
    w: 0.1




