defaults:
  - _self_
  - optimizer: adam.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m_encodig: True
encoder_cfg: 
  network_type: 'KAN'
  hddn_dim: [10, 10]
  grid: 5
  k: 3
decoder_cfg:
  network_type: 'KAN'
  hddn_dim: [10, 10]
  grid: 5
  k: 3
latent_norm: True
latent_dim: 8

loss_cfg:
  reco: 
    w: 1
  DisCO_loss_cfg:
    w: 0.01



