defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m_encodig: True
encoder_cfg: 
  hddn_dim: [64, 64, 64, 64]
  act_h: "elu"
decoder_cfg:
  hddn_dim: [64, 64, 64, 64]
  act_h: "elu"
latent_norm: True
latent_dim: 8
loss_cfg:
  reco:
    w: 1
  DisCO_loss_cfg:
    w: 0.01
  second_derivative_smoothness:
    w: 0.002
    step: 0.01
  consistency_cont: 
    w: 0.001
  consistency_x:
    w: 0.001



