defaults:
  - _self_
  - optimizer: adam.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m_encodig: True
encoder_cfg: 
  hddn_dim: [128, 128, 128, 128]
  act_h: "prelu"
decoder_cfg:
  hddn_dim: [128, 128, 128, 128]
  act_h: "prelu"
latent_norm: True
latent_dim: 8
loss_cfg:
  reco: 
    w: 1
  consistency_x:
    w: 1
  consistency_cont: 
    w: 1
  DisCO_loss_cfg:
    w: 0.01



