defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m_encodig: True
encoder_cfg: 
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
decoder_cfg:
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
latent_norm: True
latent_dim: 8
loss_cfg:
  reco:
    w: 1
  consistency_x:
    w: 0.001
  consistency_cont: 
    w: 0.001

adversarial_cfg:
  discriminator:
    hddn_dim: [64, 64, 64, 64]
    act_h: "prelu"
    act_o: "sigmoid"
  optimizer_main: default.yaml
  optimizer_d: default.yaml
  warmup: 20
  g_loss_weight: 1.0
  every_n_steps_g: 5


