defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: constant1.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m_encodig: True
encoder_cfg: 
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
decoder_cfg:
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
latent_norm: True
latent_dim: 8
loss_cfg:
  reco:
    w: 1
  consistency_x:
    w: 0.01
  consistency_cont: 
    w: 0.01
  second_derivative_smoothness:
    w: 0.001
    step: 0.1
  clip_loss_cfg:
    clip_logit_scale: 1
    w: -0.1 # negative value for anti-clip loss

valid_plots: False


