defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

network_type: partial_context
_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m_encodig: True
encoder_cfg: 
  _target_: mattstools.mattstools.modules.DenseNetwork
  _partial_: true
  act_h: silu
  nrm: layer
  hddn_dim: 128
  num_blocks: 3
  n_lyr_pbk: 2
  do_res: True
  ctxt_in_inpt: True
  ctxt_in_hddn: True
  ctxt_in_out: False
decoder_cfg:
  _target_: mattstools.mattstools.modules.DenseNetwork
  _partial_: true
  act_h: silu
  nrm: layer
  hddn_dim: 128
  num_blocks: 3
  n_lyr_pbk: 2
  do_res: True
  ctxt_in_inpt: True
  ctxt_in_hddn: True
  ctxt_in_out: False
latent_norm: False
latent_dim: 8
loss_cfg:
  reco:
    w: 1

adversarial_cfg:
  mode: "double_discriminator_priority"
  discriminator:
    _target_: mltools.mlp.MLP
    _partial_: true
    ctxt_in_hddn: True
    ctxt_in_inpt: True
    hddn_dim: [64, 64, 64, 64]
    act_h: "prelu"
    act_o: "sigmoid"
  discriminator2:
    _target_: mltools.mlp.MLP
    _partial_: true
    hddn_dim: [64, 64, 64, 64]
    ctxt_in_hddn: True
    ctxt_in_inpt: True
    act_h: "prelu"
    act_o: "sigmoid"
  optimizer_main: default.yaml
  optimizer_d: default.yaml
  warmup: 5
  g_loss_weight: 0
  g_loss_gen_weight: 0.5
  every_n_steps_g: 1
  train_dis_in_warmup: False
  g_loss_weight_in_warmup: True
  loss_function: "binary_cross_entropy"
  scheduler: 
    scheduler_g:
      _target_: torch.optim.lr_scheduler.MultiStepLR
      _partial_: True
      milestones: [30, 100, 150, 175, 200, 250]
      gamma: 0.5
    scheduler_d:
      _target_: torch.optim.lr_scheduler.MultiStepLR
      _partial_: True
      milestones: [30, 100, 150, 175]
      gamma: 0.5
    scheduler_d2:
      _target_: torch.optim.lr_scheduler.MultiStepLR
      _partial_: True
      milestones: [30, 100, 150, 175]
      gamma: 0.5
  gradient_clip_val: 0.1

valid_plots: ${verbose_validation}