defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m_encodig: True
network_type: 'Transformer_conditional'
encoder_cfg: 
  transformer:
    _target_: mattstools.mattstools.simple_transformers.TransformerEncoder
    _partial_: true
    dim: 128
    num_layers: 4
    init_method: beit
    layer_config:
      ff_mult: 2
      num_heads: 8
  node_embd_config:
    hddn_dim: 128
    num_blocks: 1
    act_h: silu
    nrm: lyr
  outp_embd_config:
    hddn_dim: 128
    num_blocks: 1
    act_h: silu
    nrm: lyr
  ctxt_embd_config:
    hddn_dim: 128
    outp_dim: 16
    num_blocks: 1
    act_h: silu
    nrm: lyr
decoder_cfg:
  transformer:
    _target_: mattstools.mattstools.simple_transformers.TransformerEncoder
    _partial_: true
    dim: 128
    num_layers: 4
    init_method: beit
    layer_config:
      ff_mult: 2
      num_heads: 8
  node_embd_config:
    hddn_dim: 128
    num_blocks: 1
    act_h: silu
    nrm: lyr
  outp_embd_config:
    hddn_dim: 128
    num_blocks: 1
    act_h: silu
    nrm: lyr
  ctxt_embd_config:
    hddn_dim: 128
    outp_dim: 64
    num_blocks: 1
    act_h: silu
    nrm: lyr
latent_norm: False
latent_dim: 128
loss_cfg:
  reco:
    w: 1

    



