defaults:
  - _self_
  - optimizer: adam.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m: True
encoder_mlp_config: 
  network_type: 'KAN'
  hddn_dim: [10, 10]
  grid: 5
  k: 3
decoder_mlp_config:
  network_type: 'KAN'
  hddn_dim: [10, 10]
  grid: 5
  k: 3
latent_norm: True
latent_dim: 8

loss_cfg:
  loss_weights:
    loss_reco: 1

  DisCO_loss_cfg:
    weight: 0.01



