defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m_encodig: True
encoder_cfg: 
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
decoder_cfg:
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
latent_norm: True
latent_dim: 8
loss_cfg:
  reco:
    w: 1
  consistency_x:
    w: 0.001
  consistency_cont: 
    w: 0.001
  second_derivative_smoothness:
    w: 0.0001
    step: 0.1

adversarial_cfg:
  mode: "default"
  discriminator:
    hddn_dim: [64, 64, 64, 64]
    act_h: "prelu"
    act_o: "sigmoid"
  optimizer_main: default.yaml
  optimizer_d: default.yaml
  warmup: 20
  g_loss_weight: 0.2
  every_n_steps_g: 1
  train_dis_in_warmup: False
  g_loss_weight_in_warmup: True
  loss_function: "mse"
  scheduler: 
    scheduler_g:
      _target_: torch.optim.lr_scheduler.MultiStepLR
      _partial_: True
      milestones: [50, 100, 150, 200, 250, 300]
      gamma: 0.5
    scheduler_d:
      _target_: torch.optim.lr_scheduler.MultiStepLR
      _partial_: True
      milestones: [50, 100, 150, 200, 250, 300]
      gamma: 0.5
  gradient_clip_val: 0.1

valid_plots: True