defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m: True
encoder_mlp_config: 
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
decoder_mlp_config:
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
latent_norm: False
latent_dim: 8


loss_cfg:
  loss_weights:
    loss_reco: 1
  latent_variance_cfg:
    weight: 1
    pow: 1
  DisCO_loss_cfg:
    weight: 0.01


# twinturbo_reco_DisCo_nonormvar