defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m_encodig: True
encoder_cfg: 
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
decoder_cfg:
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
latent_norm: False
latent_dim: 8


loss_cfg:
  reco:
    w: 1
  latent_variance_cfg:
    w: 1
    pow: 1
  DisCO_loss_cfg:
    w: 0.01


# twinturbo_reco_DisCo_nonormvar