defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m: True
encoder_mlp_config: 
  hddn_dim: [64, 64, 64, 64]
  act_h: "elu"
decoder_mlp_config:
  hddn_dim: [64, 64, 64, 64]
  act_h: "elu"
latent_norm: True
latent_dim: 8
loss_cfg:
  reco:
    w: 1
  DisCO_loss_cfg:
    w: 
      _target_: twinturbo.src.models.loss_annealing.SigmoidAnnealing
      start: 2000
      end: 75000
      min_val: 0
      amplitude: 0.01
  second_derivative_smoothness:
    step: 0.01
    w: 
      _target_: twinturbo.src.models.loss_annealing.SigmoidAnnealing
      start: 30000
      end: 85000
      min_val: 0
      amplitude: 0.01
  consistency_cont: 
    w: 0.001
  consistency_x:
    w: 0.001

