defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m: True
encoder_mlp_config: 
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
decoder_mlp_config:
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
latent_norm: True
latent_dim: 8
loss_cfg:
  reco:
    w: 1
  consistency_x:
    w: 0.01
  consistency_cont: 
    w: 0.01
  second_derivative_smoothness:
    w: 0.001
    step: 0.1

adversarial_cfg:
  discriminator:
    hddn_dim: [64, 64, 64, 64]
    act_h: "prelu"
  optimizer_main: default.yaml
  optimizer_d: default.yaml
  warmup: 20
  g_loss_weight: 0.2
  every_n_steps_g: 1
  train_dis_in_warmup: False
  g_loss_weight_in_warmup: False

