defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m: True
encoder_mlp_config: 
  hddn_dim: [128, 128, 128, 128]
  act_h: "prelu"
decoder_mlp_config:
  hddn_dim: [128, 128, 128, 128]
  act_h: "prelu"
latent_norm: True
latent_dim: 8
loss_cfg:
  loss_weights:
    loss_reco: 1
    loss_back_vec: 0.05
    loss_back_cont: 0.05
  DisCO_loss_cfg:
    weight: 0.01



