defaults:
  - _self_
  - optimizer: default.yaml
  - scheduler: cyclic.yaml

_target_: twinturbo.src.models.twinturbo_model.TwinTURBO
use_m: True
encoder_mlp_config: 
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
decoder_mlp_config:
  hddn_dim: [64, 64, 64, 64]
  act_h: "prelu"
latent_norm: True
latent_dim: 8

loss_cfg:
  reco:
    w: 1
  attractive:
    w: 0.01
  repulsive:
    w: 0.01
  consistency_x:
    w: 0.1
  consistency_cont:
    w: 0.1
  vic_reg_cfg:
    sim_coeff: 1
    std_coeff: 1
    cov_coeff: 1

