# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: gitlab-registry.cern.ch/geneva-anomalous-jets/docker/conversion:latest

before_script:
  - python --version  # For debugging

stages:
  - linting
  - unit_tests

lint:
  stage: linting
  allow_failure: true
  script:
    - find -name '*.py' | xargs python -m pylint
  rules:
    - if: $CI_COMMIT_BRANCH != ""
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"


unit_test_kinematic_functions:
  stage: unit_tests
  script:
    - python -m pytest -v
  rules:
    - if: $CI_COMMIT_BRANCH != ""
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
