datamodule:
  _target_: twinturbo.src.data.data.SimpleDataModule
  train_frac: 0.8
  train_data:
    _target_: twinturbo.src.data.data.InMemoryDataMergeClasses
    do_shuffle: true
    plotting_path: ${general.run_dir}/plots/train_autorev_data_gauss4/
    dataset_list:
      - ${data.train_cwola.experimental_data}
      - _target_: twinturbo.src.data.data.InMemoryDataFrameDict
        file_path: "/home/users/o/oleksiyu/WORK/hyperproject/dummydata/gauss_sph_4.h5"
        plotting_path: ${general.run_dir}/plots/cwola_template/
        list_order: ["data"]
  loader_kwargs:
    pin_memory: true
    batch_size: 512
    num_workers: 8 
    drop_last: false
  

input_path: /srv/beegfs/scratch/users/l/leighm/linearresults/
mode: standard
num_signal: 3000
sideband_1: [3100, 3300]
sideband_2: [3700, 3900]
num_folds: 5
max_iter: 250
early_stopping: True
validation_fraction: 0.1
class_weight: balanced
num_ensemble: 5
seed: 0