cwola_path: ${general.run_dir}/cwola/

datasets:
  datasr: ${data.cwola.datasr_0}
  extra_signal: ${data.cwola.extra_signal_0}
  template:
    _target_: twinturbo.src.data.data.InMemoryDataFrameDict
    plotting_path: ${general.run_dir}/plots/inputs/cwola/template/
    list_order: ["data"]
    file_path: ${general.run_dir}/template/outputs/template_sample_con0.h5
    processor_cfg: 
      - _target_: twinturbo.src.data.data.ProcessorSplitDataFrameVars
        frame_name: "template"
        new_df_dict: {"template": ['m_j1', 'del_m', 'del_R', 'tau21_j1', "tau21_j2", "m_jj"]}
      - _target_: twinturbo.src.data.data.ProcessorAddColumn
        frame_name: "template"
        column_name: "is_signal"
        column_values: 0


input_path: /srv/beegfs/scratch/users/l/leighm/linearresults/
mode: standard
num_signal: 0
sideband_1: 3100_3300
sideband_2: 3700_3900
num_folds: 5
max_iter: 250
early_stopping: 1
validation_fraction: 0.1
class_weight: balanced
num_ensemble: 5
seed: 0