image_build:
    stage: build
    variables:
      DESTINATION_FLAG: "--no-push"
      IMAGENAME: linear-anomaly

    rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
          - docker/Dockerfile
          - docker/requirements.txt
      - if: $CI_COMMIT_REF_NAME == "master"
        changes:
          - docker/Dockerfile
          - docker/requirements.txt
      - if: $CI_COMMIT_REF_NAME == "dev_deb"
        changes:
          - docker/Dockerfile
          - docker/requirements.txt
        variables:
          DESTINATION_FLAG: "--destination ${CI_REGISTRY_IMAGE}/${IMAGENAME}:dev"
      - if: $CI_COMMIT_TAG
        variables:
          DESTINATION_FLAG: "--destination ${CI_REGISTRY_IMAGE}/${IMAGENAME}:${CI_COMMIT_TAG}"
    image:
        name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
        entrypoint: [""]
    script:
      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor --context $CI_PROJECT_DIR/docker --dockerfile $CI_PROJECT_DIR/docker/Dockerfile $DESTINATION_FLAG
      - echo "Image \"$IMAGENAME\" successfully built with destination flag $DESTINATION_FLAG"
