_target_: autorew.src.mlp.MLPClassifier
hidden_sizes: [100, 100, 100]
num_classes: 2
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.0e-4
  weight_decay: 1.0e-5
scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: True
    T_max: 100_000
    last_epoch: -1
    eta_min: 0
  lightning:
    monitor: valid/vall_loss
    interval: step
    frequency: 1
