# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCO_DEFAULT_speed
  - step_train_template: transit_reco_adv_speed
  - step_export_template: transit_LHCO
  - step_export_SB1: transit_LHCO
  - step_export_SB2: transit_LHCO
  - step_evaluate: transit_LHCO_fast
  - step_cwola: BDT_LHCO_allCWOLA
  - step_export_latent: transit_LHCO
  - step_plot_compare: transit_LHCO
  - override step_train_template/model: TRANSIT_compile
  - override step_train_template/trainer: 200e_noclip.yaml
  - override step_train_template/model/optimizer: AdamW_lr2-4


step_train_template:
  model:
    reverse_pass_mode: additional_input
    valid_plots: False
    afterglow_epoch: 999999999

do_train_template: True
do_export_template: True
do_export_latent: True
do_evaluation: True
do_cwola: True
do_evaluate_cwola: True
do_plot_compare: True

do_transport_sideband: True

verbose_validation: False

general:
  name: TRANSITv25f_speed
  subfolder: PAPER_TEST/
  seed: 12345 # For reproducibility
  run_dir: workspaces/${general.subfolder}${general.name}
