scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: True
  milestones: [100, 200, 300, 400, 500, 600, 700, 800, 900]
  gamma: 0.5
lightning:
  monitor: valid/log_prob
  interval: step
  frequency: 1
