load_path: null
batch_size: 128
lr: 1e-4
nepochs: 20
flow4flow: delta
gclip: 5
nstack: 4
nblocks: 2
nnodes: 128
nbins: 8
activation: relu
coupling: False
coupling_width: 32
coupling_depth: 2
penalty: null
penalty_weight: 1
penalty_anneal: 1