scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: True
  milestones: [50, 100, 150, 200, 250, 300, 350]
  gamma: 0.5
lightning:
  monitor: valid/log_prob
  interval: step
  frequency: 1
